baseURL = "https://austingregory.tech/"
languageCode = "en-us"

[params]
title = "Austin Gregory"
author = "Austin Gregory"
description = "IT Support Technician"
profilePicture = "images/profile.jpg"


[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/austinggregory/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:aag5194@outlook.com"


[[params.socialIcons]]
icon = "fas fa-home"
title = "Home"
url = "/"




